#!/bin/bash

# TODO figure out whether suspend must actually be disabled

pw-cli create-node adapter '{ object.linger=1 factory.name=api.alsa.pcm.source node.name="Inferno source" media.class=Audio/Source api.alsa.path="inferno:RX_CHANNELS=24,TX_CHANNELS=24" session.suspend-timeout-seconds=0 node.pause-on-idle=false node.suspend-on-idle=false node.always-process=true api.alsa.headroom=128 api.alsa.pcm.card=999 }'
