/* SonusGrid C ABI for the inferno_aoip Dante engine.
   Generated by cbindgen — do not edit. */


#ifndef INFERNO_C_H
#define INFERNO_C_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/**
 * Status codes returned by every entry point. 0 == success.
 */
typedef enum {
  Ok = 0,
  InvalidArg = 1,
  NotInitialized = 2,
  AlreadyRunning = 3,
  NotRunning = 4,
  NotImplemented = 99,
} inferno_InfernoStatus;

/**
 * Opaque handle returned by `inferno_init`. The Swift HAL plugin treats
 * this as `OpaquePointer` and never dereferences it.
 */
typedef struct {
  uint8_t _private[0];
} inferno_InfernoHandle;

/**
 * Configuration passed to `inferno_init`.
 *
 * `name`, `bind_ip`, `interface_name` are NUL-terminated UTF-8 strings.
 * The shim copies the buffers internally; the caller may free them after
 * the call returns.
 */
typedef struct {
  /**
   * Device name visible on the Dante network (e.g. "SonusGrid-Virtual").
   */
  const char *name;
  /**
   * Bind IP — explicit IPv4 string, or NULL to auto-pick.
   */
  const char *bind_ip;
  /**
   * Network interface short name (e.g. "en0").
   */
  const char *interface_name;
  unsigned int sample_rate;
  unsigned int rx_channels;
  unsigned int tx_channels;
  uint64_t rx_latency_ns;
  uint64_t tx_latency_ns;
  /**
   * Path to the usrvclock UNIX socket the PTP daemon exposes. NULL if
   * using system clock fallback.
   */
  const char *clock_socket_path;
} inferno_InfernoConfig;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Initialize the shim and allocate runtime resources. Returns a handle on
 * success, or NULL if `cfg` is invalid.
 *
 * Not realtime-safe — call from setup code, not from an audio callback.
 */
inferno_InfernoHandle *inferno_init(const inferno_InfernoConfig *_cfg);

/**
 * Begin advertising the device on the network and accepting subscriptions.
 */
inferno_InfernoStatus inferno_start(inferno_InfernoHandle *_h);

/**
 * Stop network activity but keep the handle alive (re-startable).
 */
inferno_InfernoStatus inferno_stop(inferno_InfernoHandle *_h);

/**
 * Tear down everything and free `h`. After this call `h` is invalid.
 */
inferno_InfernoStatus inferno_shutdown(inferno_InfernoHandle *h);

/**
 * Realtime-safe TX block push. Audio thread copies `frames * channels`
 * samples (interleaved f32) into the internal ring buffer.
 *
 * # Safety
 *
 * `samples` must point to at least `frames * channels` valid f32 values.
 */
inferno_InfernoStatus inferno_push_tx_block(inferno_InfernoHandle *_h,
                                            const float *samples,
                                            unsigned int frames,
                                            unsigned int channels);

/**
 * Realtime-safe RX block pull. Audio thread receives `frames * channels`
 * samples (interleaved f32). Underrun fills with silence.
 *
 * # Safety
 *
 * `samples` must point to writable memory of at least `frames * channels`
 * f32 values.
 */
inferno_InfernoStatus inferno_pull_rx_block(inferno_InfernoHandle *_h,
                                            float *samples,
                                            unsigned int frames,
                                            unsigned int channels);

/**
 * Returns library version string, never NULL, never freed.
 */
const char *inferno_version(void);

/**
 * Returns the size of the InfernoConfig struct so the caller can sanity-check
 * that header and library agree on layout.
 */
int inferno_config_size(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* INFERNO_C_H */
