// SPDX-License-Identifier: GPL-3.0-or-later
//! ALSA-side configuration: render `~/.config/alsa/sonusgrid.conf` from the
//! user's SonusGrid config and ensure `~/.asoundrc` includes it (idempotent).
//!
//! We never overwrite the user's own asoundrc. We add (or update) a single
//! marked block:
//!
//!     # >>> sonusgrid  (managed; do not edit between markers)
//!     <~/.config/alsa/sonusgrid.conf>
//!     # <<< sonusgrid

use anyhow::{Context, Result};
use std::fs;
use std::path::PathBuf;
use std::process::Command;

use crate::config::Config;
use crate::paths;

/// Look up the current IPv4 address of a network interface by name.
/// Returns None if the interface is down or has no IPv4. We resolve this
/// at every `sonusgrid start` so DHCP-renewed IPs are picked up automatically
/// (the engine binds by exact IP, so a stale saved IP would panic at startup).
pub fn interface_ipv4(name: &str) -> Option<String> {
    if name.is_empty() {
        return None;
    }
    let out = Command::new("ip")
        .args(["-j", "addr", "show", "dev", name])
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    let v: serde_json::Value = serde_json::from_slice(&out.stdout).ok()?;
    let arr = v.as_array()?;
    let entry = arr.first()?;
    let addrs = entry.get("addr_info")?.as_array()?;
    for a in addrs {
        if a.get("family")?.as_str()? == "inet" {
            if let Some(local) = a.get("local").and_then(|x| x.as_str()) {
                return Some(local.to_string());
            }
        }
    }
    None
}

const BEGIN_MARKER: &str = "# >>> sonusgrid  (managed; do not edit between markers)";
const END_MARKER: &str = "# <<< sonusgrid";

fn alsa_conf_path() -> Result<PathBuf> {
    let p = dirs::config_dir()
        .ok_or_else(|| anyhow::anyhow!("$HOME not set; cannot find config dir"))?
        .join("alsa")
        .join("sonusgrid.conf");
    Ok(p)
}

fn asoundrc_path() -> Result<PathBuf> {
    let h = dirs::home_dir().ok_or_else(|| anyhow::anyhow!("$HOME not set"))?;
    Ok(h.join(".asoundrc"))
}

pub fn install_user_asoundrc(cfg: &Config) -> Result<()> {
    let alsa_conf = alsa_conf_path()?;
    if let Some(parent) = alsa_conf.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&alsa_conf, render_alsa_conf(cfg))
        .with_context(|| format!("writing {}", alsa_conf.display()))?;

    let asoundrc = asoundrc_path()?;
    let existing = fs::read_to_string(&asoundrc).unwrap_or_default();
    let block = format!(
        "{BEGIN_MARKER}\n<{}>\n{END_MARKER}\n",
        alsa_conf.display()
    );

    let updated = update_block(&existing, &block);
    fs::write(&asoundrc, updated).with_context(|| format!("writing {}", asoundrc.display()))?;
    Ok(())
}

fn update_block(existing: &str, new_block: &str) -> String {
    if let (Some(begin), Some(end)) = (existing.find(BEGIN_MARKER), existing.find(END_MARKER)) {
        let end_after = end + END_MARKER.len();
        // Trim a trailing newline if present.
        let end_after = if existing[end_after..].starts_with('\n') {
            end_after + 1
        } else {
            end_after
        };
        let mut out = String::with_capacity(existing.len() + new_block.len());
        out.push_str(&existing[..begin]);
        out.push_str(new_block);
        out.push_str(&existing[end_after..]);
        out
    } else if existing.is_empty() {
        new_block.to_string()
    } else {
        let mut out = existing.to_string();
        if !out.ends_with('\n') {
            out.push('\n');
        }
        out.push_str(new_block);
        out
    }
}

fn render_alsa_conf(cfg: &Config) -> String {
    // Always re-resolve the interface's *current* IPv4 — the saved bind_ip
    // becomes stale the moment DHCP renews and the engine panics binding to
    // a non-existent address. Order of preference:
    //   1. live IPv4 of the configured interface (always wins if present)
    //   2. saved bind_ip from config (last known good)
    //   3. interface name (Inferno accepts this as a bind hint)
    let resolved = interface_ipv4(&cfg.network.interface);
    let bind_ip_owned: String = match (resolved, !cfg.network.bind_ip.is_empty()) {
        (Some(ip), _) => ip,
        (None, true) => cfg.network.bind_ip.clone(),
        (None, false) => cfg.network.interface.clone(),
    };
    let bind_ip: &str = bind_ip_owned.as_str();
    let clock_path = paths::clock_socket_path();
    format!(
        r#"# Generated by `sonusgrid` — do not edit by hand.
# Source of truth: ~/.config/sonusgrid/config.toml
# Compatible with Dante audio networks; not affiliated with Audinate Pty Ltd.

pcm.sonusgrid {{
    type sonusgrid
    NAME            "{name}"
    SAMPLE_RATE     "{rate}"
    RX_CHANNELS     "{rx}"
    TX_CHANNELS     "{tx}"
    BIND_IP         "{bind}"
    RX_LATENCY_NS   "{rx_lat}"
    TX_LATENCY_NS   "{tx_lat}"
    CLOCK_PATH      "{clock}"
    hint {{
        show on
        description "SonusGrid virtual audio device"
    }}
}}

# Stereo plug for apps that don't speak {rx}-channel S32 (e.g. Audacity).
pcm.sonusgrid_stereo {{
    type plug
    slave.pcm "sonusgrid"
}}
"#,
        name = cfg.device.name,
        rate = cfg.device.sample_rate,
        rx = cfg.device.rx_channels,
        tx = cfg.device.tx_channels,
        bind = bind_ip,
        rx_lat = cfg.device.rx_latency_ns,
        tx_lat = cfg.device.tx_latency_ns,
        clock = clock_path.display(),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn block_inserted_in_empty_file() {
        let block = "# >>> sonusgrid  (managed; do not edit between markers)\n<x>\n# <<< sonusgrid\n";
        assert_eq!(update_block("", block), block);
    }

    #[test]
    fn block_replaces_old_block() {
        let existing = "before\n# >>> sonusgrid  (managed; do not edit between markers)\nold\n# <<< sonusgrid\nafter\n";
        let new = "# >>> sonusgrid  (managed; do not edit between markers)\nNEW\n# <<< sonusgrid\n";
        let out = update_block(existing, new);
        assert!(out.contains("NEW"));
        assert!(!out.contains("old"));
        assert!(out.starts_with("before\n"));
        assert!(out.contains("after\n"));
    }

    #[test]
    fn block_appended_when_missing() {
        let existing = "user line\n";
        let new = "# >>> sonusgrid  (managed; do not edit between markers)\nA\n# <<< sonusgrid\n";
        let out = update_block(existing, new);
        assert!(out.starts_with("user line\n"));
        assert!(out.ends_with("# <<< sonusgrid\n"));
    }
}
