// SPDX-License-Identifier: GPL-3.0-or-later
//! PTP daemon (Statime) configuration rendering.
//!
//! Statime is shipped as `/usr/libexec/sonusgrid/statime` with `cap_sys_time`
//! set by the .deb postinst (or by `make install`). It reads a TOML file we
//! render here to a cache path the user can also inspect.

use anyhow::{Context, Result};
use std::path::PathBuf;

use crate::config::Config;
use crate::paths;

pub fn statime_config_path() -> PathBuf {
    dirs::cache_dir()
        .unwrap_or_else(std::env::temp_dir)
        .join("sonusgrid")
        .join("statime.toml")
}

pub fn render_statime_config(cfg: &Config) -> Result<PathBuf> {
    if cfg.network.interface.is_empty() {
        anyhow::bail!(
            "no network interface configured — run `sonusgrid config edit` or pick one in the GUI"
        );
    }
    let iface = cfg.network.interface.clone();
    let proto = match cfg.ptp.version.as_str() {
        "v2" => "PTPv2",
        _ => "PTPv1",
    };
    let socket = paths::clock_socket_path();
    let observe = paths::observe_socket_path();
    let body = format!(
        r#"# Generated by `sonusgrid` — do not edit by hand.
loglevel = "info"

sdo-id = 0
domain = {domain}
priority1 = {priority1}
virtual-system-clock = true
virtual-system-clock-base = "monotonic_raw"
usrvclock-export = true
usrvclock-path = "{socket}"

[observability]
observation-path = "{observe}"
observation-permissions = 0o600

[[port]]
interface = "{iface}"
network-mode = "ipv4"
hardware-clock = "{hw}"
protocol-version = "{proto}"
"#,
        domain = cfg.ptp.domain,
        priority1 = cfg.ptp.priority1,
        socket = socket.display(),
        observe = observe.display(),
        iface = iface,
        hw = cfg.ptp.hardware_clock,
        proto = proto,
    );
    let path = statime_config_path();
    if let Some(p) = path.parent() {
        std::fs::create_dir_all(p)?;
    }
    std::fs::write(&path, body).with_context(|| format!("writing {}", path.display()))?;
    Ok(path)
}

/// Remove leftover Unix-socket files from prior Statime runs. Statime panics
/// with `AddrInUse` when binding to an existing socket path; the kernel does
/// not unlink the socket file on process death.
///
/// Only touches our own runtime directory (plus the legacy `/tmp` socket
/// from 0.2.0 and earlier, best-effort).
pub fn cleanup_usrvclock_sockets() {
    use std::fs;
    let _ = fs::remove_file(paths::clock_socket_path());
    let _ = fs::remove_file(paths::observe_socket_path());
    let _ = fs::remove_file(paths::LEGACY_CLOCK_SOCKET);
    if let Ok(entries) = fs::read_dir(paths::runtime_dir()) {
        for e in entries.flatten() {
            let name = e.file_name();
            let name = name.to_string_lossy();
            if name.starts_with("usrvclock-") {
                let _ = fs::remove_file(e.path());
            }
        }
    }
}

/// Block until Statime publishes its first clock overlay (= PTP lock
/// achieved), or `timeout` elapses. Returns true on success.
///
/// Without this the audio bridge starts the instant the clock *process*
/// is up, the engine waits 5 s for an overlay, gives up, and systemd has to
/// restart the bridge — every single start looked like a crash.
pub fn wait_for_clock(timeout: std::time::Duration) -> bool {
    use std::sync::mpsc;
    let socket = paths::clock_socket_path();
    // The client creates its reply socket in $TMPDIR; keep it in our
    // runtime dir, next to the server socket.
    std::env::set_var("TMPDIR", paths::runtime_dir());
    let (tx, rx) = mpsc::channel();
    std::thread::spawn(move || {
        let mut client = usrvclock::BlockingClient::new(socket);
        let ok = client.recv().is_ok();
        let _ = tx.send(ok);
    });
    let t0 = std::time::Instant::now();
    eprintln!("[sonusgrid] waiting for PTP clock lock (up to {}s)…", timeout.as_secs());
    let ok = rx.recv_timeout(timeout).unwrap_or(false);
    if ok {
        eprintln!("[sonusgrid] PTP clock ready after {:.1}s", t0.elapsed().as_secs_f32());
    } else {
        eprintln!("[sonusgrid] no PTP clock after {}s — starting the bridge anyway", timeout.as_secs());
    }
    // Drop the reply socket file(s) this process created.
    let prefix = format!("usrvclock-client.{}.", std::process::id());
    if let Ok(entries) = std::fs::read_dir(paths::runtime_dir()) {
        for e in entries.flatten() {
            if e.file_name().to_string_lossy().starts_with(&prefix) {
                let _ = std::fs::remove_file(e.path());
            }
        }
    }
    ok
}


/// Snapshot of the PTP instance as reported by Statime's observation socket.
#[derive(Debug, Clone, serde::Serialize, Default)]
pub struct PtpObservation {
    /// `Slave`, `Master`, `Listening`, `Uncalibrated`, … (IEEE 1588 port state).
    pub state: String,
    /// True when the port is synchronised to a master (or is the master) and
    /// the clock overlay is being published to the engine.
    pub locked: bool,
    pub offset_ns: Option<f64>,
    pub mean_delay_ns: Option<f64>,
    pub steps_removed: Option<u16>,
    pub grandmaster: Option<String>,
    pub uptime_s: Option<f64>,
}

/// Connect to Statime's observation socket and decode the current state.
/// Returns None if Statime isn't running or the socket doesn't answer within
/// the (short) timeout — callers treat that as "unknown", never as an error.
pub fn observe() -> Option<PtpObservation> {
    use std::io::Read;
    use std::os::unix::net::UnixStream;
    use std::time::Duration;

    let path = paths::observe_socket_path();
    let mut stream = UnixStream::connect(&path).ok()?;
    let _ = stream.set_read_timeout(Some(Duration::from_millis(500)));
    let mut buf = String::new();
    stream.read_to_string(&mut buf).ok()?;
    let v: serde_json::Value = serde_json::from_str(&buf).ok()?;
    let inst = v.get("instance")?;

    // Statime serialises `Duration` as the raw bits of an I96F32 fixed-point
    // nanosecond value, i.e. ns = bits / 2^32.
    fn fixed_ns(v: Option<&serde_json::Value>) -> Option<f64> {
        let bits = v?.as_i64().map(|x| x as f64).or_else(|| v?.as_f64())?;
        Some(bits / 4_294_967_296.0)
    }
    fn clock_id(v: Option<&serde_json::Value>) -> Option<String> {
        match v? {
            serde_json::Value::Array(bytes) => Some(
                bytes.iter()
                    .filter_map(|b| b.as_u64())
                    .map(|b| format!("{b:02x}"))
                    .collect::<Vec<_>>()
                    .join(""),
            ),
            serde_json::Value::String(s) => Some(s.clone()),
            other => Some(other.to_string()),
        }
    }

    let state = inst
        .get("port_ds")
        .and_then(|p| p.as_array())
        .and_then(|a| a.first())
        .and_then(|p| p.get("port_state"))
        .map(|s| match s {
            serde_json::Value::String(s) => s.clone(),
            other => other.to_string(),
        })
        .unwrap_or_else(|| "Unknown".into());
    let cur = inst.get("current_ds");
    let par = inst.get("parent_ds");
    let synced = matches!(state.as_str(), "Slave" | "Master");
    Some(PtpObservation {
        locked: synced && paths::clock_socket_path().exists(),
        state,
        offset_ns: fixed_ns(cur.and_then(|c| c.get("offset_from_master"))),
        mean_delay_ns: fixed_ns(cur.and_then(|c| c.get("mean_delay"))),
        steps_removed: cur
            .and_then(|c| c.get("steps_removed"))
            .and_then(|x| x.as_u64())
            .map(|x| x as u16),
        grandmaster: clock_id(par.and_then(|p| p.get("grandmaster_identity"))),
        uptime_s: v.get("program").and_then(|p| p.get("uptime_seconds")).and_then(|x| x.as_f64()),
    })
}
