// SPDX-License-Identifier: GPL-3.0-or-later
//
// InfernoBridge — Swift wrapper around the libinferno_c.dylib C ABI.
//
// Hides every `OpaquePointer` and `UnsafeMutablePointer` from the rest of
// the HAL plugin. Realtime callers go through `pushTX` / `pullRX`, which
// call the C functions directly without locking.
//

import Foundation

// The C declarations live in `inferno.h` (generated by cbindgen). When
// added to an Xcode target, set `SWIFT_OBJC_BRIDGING_HEADER` to a header
// that #imports "inferno.h", and link `libinferno_c.dylib` from the
// `.driver/Contents/Frameworks/` directory.

public final class InfernoBridge {
    public struct Config {
        public var name: String
        public var bindIP: String?
        public var interfaceName: String
        public var sampleRate: UInt32
        public var rxChannels: UInt32
        public var txChannels: UInt32
        public var rxLatencyNS: UInt64
        public var txLatencyNS: UInt64
        public var clockSocketPath: String?

        public init(
            name: String, bindIP: String?, interfaceName: String,
            sampleRate: UInt32, rxChannels: UInt32, txChannels: UInt32,
            rxLatencyNS: UInt64, txLatencyNS: UInt64,
            clockSocketPath: String?
        ) {
            self.name = name
            self.bindIP = bindIP
            self.interfaceName = interfaceName
            self.sampleRate = sampleRate
            self.rxChannels = rxChannels
            self.txChannels = txChannels
            self.rxLatencyNS = rxLatencyNS
            self.txLatencyNS = txLatencyNS
            self.clockSocketPath = clockSocketPath
        }
    }

    public enum Status: Int32 {
        case ok = 0, invalidArg = 1, notInitialized = 2,
             alreadyRunning = 3, notRunning = 4, notImplemented = 99
    }

    private var handle: OpaquePointer?
    private let lock = NSLock()

    public init?(config cfg: Config) {
        // Convert Swift Strings to C strings; lifetimes must outlive the
        // call. The C side is documented to copy what it needs.
        let nameCS = cfg.name.cString(using: .utf8)
        let bindCS = cfg.bindIP?.cString(using: .utf8)
        let ifaceCS = cfg.interfaceName.cString(using: .utf8)
        let clockCS = cfg.clockSocketPath?.cString(using: .utf8)

        // The `inferno_init` call is in C land — gated by `#if canImport`
        // because Swift Package Manager / Xcode targets that don't yet
        // link libinferno_c will skip this path during the early HAL plugin
        // skeleton phase. Fill in once the bridging header is wired.
        //
        // var c = inferno_InfernoConfig(...)
        // self.handle = inferno_init(&c)
        //
        // For the skeleton, fail closed:
        _ = (nameCS, bindCS, ifaceCS, clockCS)
        self.handle = nil
        return nil
    }

    deinit {
        if handle != nil {
            // inferno_shutdown(handle)
        }
    }

    // MARK: - Realtime hot path
    //
    // Both `pushTX` and `pullRX` are called from the CoreAudio IO thread.
    // They MUST NOT lock, allocate, or block.

    @inline(__always)
    public func pushTX(samples: UnsafePointer<Float>, frames: UInt32, channels: UInt32) -> Int32 {
        // inferno_push_tx_block(handle, samples, frames, channels).rawValue
        return Status.notImplemented.rawValue
    }

    @inline(__always)
    public func pullRX(samples: UnsafeMutablePointer<Float>, frames: UInt32, channels: UInt32) -> Int32 {
        // inferno_pull_rx_block(handle, samples, frames, channels).rawValue
        return Status.notImplemented.rawValue
    }

    // MARK: - Setup-time

    public func start() -> Status {
        Status.notImplemented
    }

    public func stop() -> Status {
        Status.notImplemented
    }
}
