# SPDX-License-Identifier: GPL-3.0-or-later
"""SonusGrid GTK4/libadwaita front-end."""

try:
    from sonus_gtk._version import __version__  # generated by `make build-gui`
except ImportError:  # running from a bare checkout
    __version__ = "0.0.0-dev"
